### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by vovayartsev** [errkk/ticketytock#3]
It looks like `TicketytockWeb.WebhookController#event` accepts webhooks from all over the world. `Payment Intent ID` can be easily found in network details (e.g. when trying to pay with an empty credit card )
![image](https://user-images.githubusercontent.com/204231/73734662-6cb8d200-4757-11ea-8f93-60cae341eef9.png)
 So it seems to be possible to get a ticket for free. 👿 

Can you please propose a solution? No need to write the code - but please explain your fix in details (as if you were explaining to a colleague and wanted to make sure there's no second reading of that explanation)

**Comment by errkk** [comment]
Ah yes good spot.
A few things I could do here:

- Firstly, it would be worth verifying the client_secret that gets send back from Stripe to make sure it's them sending the request, and regarding this intent.

- To be extra sure, I'd filter access to this endpoint in production environment to allow only access from a range of known Stripe [webhook-hitting IPs](https://stripe.com/docs/ips#webhook-ip-addresses). So at a networking/firewall level could be a nice place to implement this (if not in the code/host for smaller deployments).

**Comment by vovayartsev** [comment]
Yep, that's all valid solutions. Accepted!

In DICE we rely on the signatures from Stripe - https://stripe.com/docs/webhooks/signatures
